services:
  - type: web
    name: precificacao-sistema
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
    autoDeploy: true 